### ISSUE TITLE
evaluate different loss types

### ISSUE THREAD

**Issue by dapetri** [alr-internship/self-supervised-depth-denoising#22]
Default delta for huber loss is 1. which means differences between target and prediction bigger than 1 mm will be in treated as l1 loss. maybe it makes more sense to expand the l2 region to bigger margin

**Comment by claudius-kienle** [comment]
![image](https://user-images.githubusercontent.com/25877269/155841519-d389623a-90ed-4e5b-9775-cc4ef0a6571c.png)
The pink curve displays the network loss trained with l1 loss.
The skin colored curve displays the network loss trained with huber loss.

The l1 loss decreases relatively fast, but stagnates quickly.
The huber loss does perform better on a long run

**Comment by claudius-kienle** [comment]
solved by random hyperparameter search
